services:
  db:
    image: postgres:13
    container_name: nest-postgres
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432
    networks:
      - nest-network
    volumes:
      - ./data/db:/var/lib/postgresql/data
networks:
  nest-network:
    driver: bridge
